# Generated by Django 2.2 on 2019-11-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=15, null=True)),
                ('shipment_ref', models.CharField(blank=True, max_length=15, null=True)),
                ('shpiment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_id', models.CharField(blank=True, max_length=15, null=True)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='shipment.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(blank=True, max_length=15, null=True)),
                ('order_id', models.CharField(blank=True, max_length=15, null=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='shipment.Shipment')),
            ],
        ),
    ]
