# Generated by Django 2.2 on 2019-11-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipmentItems',
            new_name='ShipmentItem',
        ),
    ]
