# Generated by Django 2.2 on 2019-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_auto_20191108_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
