# Generated by Django 2.2 on 2019-11-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='created',
        ),
    ]
